model:
  base_learning_rate: 4.5e-6
  target: taming.models.vqgan.VQModel
  params:
    embed_dim: 256
    n_embed: 1024
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 256
      in_channels: 6
      out_ch: 6
      ch: 128
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [12]
      dropout: 0.0
      cross_entropy: False
      
    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 6
        disc_start: 10000
        disc_weight: 0.8
        codebook_weight: 1.0
        perceptual_weight: 0
        cross_entropy: False
data:
  target: train_autoencoder.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 16
    train:
      target: taming.data.custom.CustomTrain
      params:
        training_images_list_file: gt
        size: 256
    validation:
      target: taming.data.custom.CustomTest
      params:
        test_images_list_file: gt
        size: 256

